/**
 * Runs in front of Payload's HTTP API, and only that.
 *
 * `api/[...slug]/route.ts` is generated by Payload and carries a warning
 * against editing it, so the gate cannot live there. The media file route gets
 * around that by claiming a longer static prefix — Next matches the longer one
 * first — but there is no prefix that covers the whole API, and shadowing every
 * collection one directory at a time would go stale the first time somebody
 * adds a collection.
 *
 * Here it is one file that cannot be missed, and it stops a refused request
 * before the function boots Payload and opens a database connection, which is
 * the cost this exists to cap. See `publicApiGate` for what is refused and why.
 *
 * `runtime` cannot be set in a proxy; Next 16 runs it on Node.
 */
import type { NextRequest } from 'next/server'

import { NextResponse } from 'next/server'

import { anonymousApiRefusal, isClosedToAnonymous } from '@/utilities/publicApiGate'

export const proxy = (request: NextRequest) =>
  isClosedToAnonymous(request) ? anonymousApiRefusal() : NextResponse.next()

/**
 * `/api`, less the uploads.
 *
 * Every image on the site is an `/api/media/file/...` request, answered from a
 * year-long immutable cache; putting a hop in front of those would add work to
 * the one part of this API that is already cheap. `publicApiGate` lets them
 * past as well, so a mistake in this pattern is not what decides it.
 */
export const config = {
  matcher: ['/api/((?!media/file/).*)'],
}
